<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:property name="lidar_length" value="0.05"></xacro:property>
    <xacro:property name="lidar_radius" value="0.05"></xacro:property>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"></cylinder>
            </geometry>
            <material name="grey">
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"></cylinder>
            </geometry>
        </collision>
        <xacro:cylinder_inertia r="${2*lidar_radius}" h="${2*lidar_length}" m="1.0" 
                                    xyz="0 0 0" rpy="${pi/2} 0 0" />
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${base_height+(lidar_length / 2)}" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_link">
        <material>Gazebo/Red</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray> 
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>  
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                  </noise>    
            </ray>
            <plugin name="lidar" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_link</frame_name>

                <!-- <topic_name>/scan</topic_name>
                <output_type>sensor_msgs/LaserScan</output_type> -->
                <!-- <ros>
                    <argument>~/out:=scan</argument>
                </ros> -->
                <!-- <output>sensor_msgs/LaserScan</output>
                <frame_name>laser_frame</frame_name> -->
            </plugin>
        </sensor>
    </gazebo>


</robot>